import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [counter,setCounter] = useState(0)
  const handleClick = () =>{
   setCounter((prevState) => prevState + 1)
  }
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Next.js {counter}</h1>
      <button onClick={handleClick}>Click</button>
    </div>
  )
}
